version: '3.8'

services:
  # Override Next.js for development
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: noveo-nextjs-dev
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3001:3000"
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Disable nginx for development (optional)
  nginx:
    profiles:
      - production 